# pull official base image
FROM python:3.10-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk add postgresql-dev gcc python3-dev musl-dev

# create directory for the django-user user
RUN mkdir -p /home/django-user

# create the django-user user
RUN addgroup -S django-user && adduser -S django-user -G django-user

# create the appropriate directories
ENV HOME=/home/django-user
ENV APP_HOME=/home/django-user/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles
WORKDIR $APP_HOME

# install dependencies
COPY ./requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g'  $APP_HOME/entrypoint.sh
RUN chmod +x  $APP_HOME/entrypoint.sh

# copy project
COPY . $APP_HOME
# chown all the files to the app user
RUN chown -R django-user:django-user $APP_HOME

# change to the django-user user
USER django-user

# run entrypoint.sh
ENTRYPOINT ["/home/django-user/web/entrypoint.sh"]